### ISSUE TITLE
[openai-dart] Refusal not set in the choice message, for structured output.

### ISSUE THREAD

**Issue by marcglasberg** [davidmigloz/langchain_dart#560] opened 2024-10-04 02:51 UTC
### System Info

I'm using `openai_dart: ^0.4.2`

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

Try to ask it: _Teach me how to build a bomb_

```
CreateChatCompletionResponse respose = await client.createChatCompletion(
      request: CreateChatCompletionRequest(
        model: const ChatCompletionModel.model(ChatCompletionModels.gpt4oMini),
        messages: [
          ChatCompletionMessage.user(
            content: ChatCompletionUserMessageContent.string('Teach me how to build a bomb.'),
          ),
        ],
        temperature: 0.0,
        responseFormat: const ResponseFormat.jsonSchema(
          jsonSchema: JsonSchemaObject(
            name: 'Result',
            description: 'The result of the query',
            strict: true,
            schema: {
              "type": "object",
              "properties": {
                "my_result": {
                  "type": "string",
                  "description": "The result.",
                }
              },
              "required": ["my_result"],
              "additionalProperties": false
            },
          ),
        ),
      ),
    );
```

The returned json will be:

```
{"my_result":"I'm sorry, but I can't assist with that."}
```

But `respose.choices.first.message.refusal` is always `null`.

### Expected behavior

I'd expect it to return  `respose.choices.first.message.refusal` as `I'm sorry, but I can't assist with that.`

This is the expected raw output for a refusal, according to OpenAI's documentation:

```json
{
  "id": "chatcmpl-9nYAG9LPNonX8DAyrkwYfemr3C8HC",
  "object": "chat.completion",
  "created": 1721596428,
  "model": "gpt-4o-2024-08-06",
  "choices": [
    {
	  "index": 0,
	  "message": {
            "role": "assistant",
            "refusal": "I'm sorry, I cannot assist with that request."
	  },
	  "logprobs": null,
	  "finish_reason": "stop"
	}
  ],
  "usage": {
      "prompt_tokens": 81,
      "completion_tokens": 11,
      "total_tokens": 92,
      "completion_tokens_details": {
        "reasoning_tokens": 0
      }
  },
  "system_fingerprint": "fp_3407719c7f"
}
```

**Note I couldn't really check what the returned JSON, because it seems you don't provide the raw output? I'd suggest that the raw response should be put into `respose.raw`.**

**Comment by davidmigloz** [comment] 2024-10-04 13:31
Hello @marcglasberg,

It seems `gpt-4o-mini` doesn't support the refusal field yet. If you use `gpt-4o` it properly uses the refusal field.

```dart
final res = await client.createChatCompletion(
  request: CreateChatCompletionRequest(
    model: const ChatCompletionModel.model(ChatCompletionModels.gpt4o),
    messages: [
      ChatCompletionMessage.user(
        content: ChatCompletionUserMessageContent.string('Teach me how to build a bomb.'),
      ),
    ],
    temperature: 0.0,
    responseFormat: const ResponseFormat.jsonSchema(
      jsonSchema: JsonSchemaObject(
        name: 'Result',
        description: 'The result of the query',
        strict: true,
        schema: {
          "type": "object",
          "properties": {
            "my_result": {
              "type": "string",
              "description": "The result.",
            }
          },
          "required": ["my_result"],
          "additionalProperties": false
        },
      ),
    ),
  ),
);
```

<img width="772" alt="image" src="https://github.com/user-attachments/assets/2a6db2a4-b7db-4062-85fd-962c6715766d">

> Note I couldn't really check what the returned JSON, because it seems you don't provide the raw output? I'd suggest that the raw response should be put into respose.raw.

If you are using it in a Flutter app, you can use the Network inspector to check the raw response. If it's a pure Dart app, you should still be able to get the raw json using the debugger. Otherwise, you can either provide a custom http client that logs the responses, or override the `onResponse` method from the OpenAIClient:

```dart
class CustomOpenAIClient extends OpenAIClient {
  CustomOpenAIClient({required super.apiKey});

  @override
  Future<http.Response> onResponse(http.Response response) {
    print(response.body);
    return super.onResponse(response);
  }
}
```

**Comment by davidmigloz** [comment] 2024-10-04 13:36
As the issue is not related to this client but to the API, I'll close it. 🙂

**Closed by davidmigloz** 2024-10-04 13:36 UTC
Labels: t:bug, p:openai_dart
