### ISSUE TITLE
Support ConversationalRetrievalQAChain

### ISSUE THREAD

**Issue by mirkancal** [davidmigloz/langchain_dart#108] opened 2023-08-11 12:15 UTC
### Feature request

https://js.langchain.com/docs/modules/chains/popular/chat_vector_db

### Motivation

Having conversation context for RetrievalQAChain.

### Your contribution

I'm getting more familiar with library, I'll update if I'll have a PR.

**Comment by mdshihabuddinroky** [comment] 2023-10-11 08:10
Please add this as soon as possible. Thank you

**Comment by davidmigloz** [comment] 2023-10-11 08:51
Duplicate of #52

**Closed by davidmigloz** 2023-10-11 08:51 UTC
Labels: t:enhancement, c:chains
