### ISSUE TITLE
Being able to stop api/pull models download stream

### ISSUE THREAD

**Issue by JulienElkaim** [davidmigloz/langchain_dart#568] opened 2024-10-09 11:28 UTC
### Feature request

Hi, 

I would like a feature to make it possible to cancel a pullModelStream , so Ollama stops downloading the model if we want to.

### Motivation

In my Ollama client, I want to give users the right to missclick. Therefore, if they finally decide they don't want the huge models on their computer, they can stop downloading it !

### Your contribution

Please share your preferences of implementation, and I will be happy to contribute

**Comment by davidmigloz** [comment] 2024-10-09 11:57
Hey @JulienElkaim,

Thanks for bringing this up.

The problem is that the official [http package doesn't support cancelling requests](https://github.com/dart-lang/http/issues/424) yet. Do you have any suggestions?

**Comment by JulienElkaim** [comment] 2024-10-09 12:24
Hi,

Interesting for an official http package!
I understand they feel it's negligible most of time... but with models that size the stake is high. As official library they should support these edge cases :/ 

I would hope we can support it. I tried with curls & ctrl+C and it confirms cancelling http request stops download, see screenshot:
<img width="1105" alt="Screenshot 2024-10-09 at 8 18 44 PM" src="https://github.com/user-attachments/assets/c6c7c314-9595-4db0-b9d4-a44a513c8476">


Could we switch http library? I did not dig into your codebase yet so I am not sure how big it is.
If you like the idea, I can do further analysis. **It seems [dio package support cancellation](https://pub.dev/packages/dio#cancellation), If I understand correctly.**

- **How open would you be to switch to dio?** 
- **Do you prefer the same http package dependency for ALL Ollama calls or can we only switch library for api/pull ?**

I can give a try with dio and provide an example  next week. See if switching library is worth it before doing anything :)

**Comment by davidmigloz** [comment] 2024-10-09 12:55
I agree, it's a pity that such a basic feature is still not supported.

Migrating to another client would have quite some impact, as we generate the client from the OpenAPI spec using the [openapi_spec](https://pub.dev/packages/openapi_spec) generator. So, first we would need to add support for different clients in the generator... And using different clients for different methods would be a bit confusing, I think. 

Do you know if there is any alternative that wraps the official http client and adds support for cancelling requests without modifying its API? That would be an ideal solution, as you can always pass your custom http client:
```dart
final client = OllamaClient(
  client: CancellableHttpClient(),
);
```

**Comment by davidmigloz** [comment] 2024-10-09 13:01
An example would be https://pub.dev/packages/fetch_client (which is used internally by OllamaClient when targetting web to support streaming). It implements the same http API, but under-the-hood it uses the JS fetch API which supports cancelling requests.

**Comment by davidmigloz** [comment] 2024-12-21 22:11
I'll close this issue for now, as it's not actionable at the moment. We'll reconsider it if http package adds the needed functionality or if we decide to migrate to a different http client.

**Closed by davidmigloz** 2024-12-21 22:11 UTC
Labels: t:enhancement, p:ollama_dart
